// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPxVGBgO8g8ysG8t2V6eMOXX3KBn1j5lY',
    appId: '1:214317871931:web:36924755ba857126753d1e',
    messagingSenderId: '214317871931',
    projectId: 'ticket-event-edc21',
    authDomain: 'ticket-event-edc21.firebaseapp.com',
    storageBucket: 'ticket-event-edc21.firebasestorage.app',
    measurementId: 'G-G68E9SHFHV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdBZnQXUMZK6U1PW_UG-5ntVOKxKyNh2E',
    appId: '1:214317871931:android:ab453e50c8789fd0753d1e',
    messagingSenderId: '214317871931',
    projectId: 'ticket-event-edc21',
    storageBucket: 'ticket-event-edc21.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdZsrB1QgXiPOKe-xjj6AlM44gK0TdNAY',
    appId: '1:214317871931:ios:77280a431234c300753d1e',
    messagingSenderId: '214317871931',
    projectId: 'ticket-event-edc21',
    storageBucket: 'ticket-event-edc21.firebasestorage.app',
    iosBundleId: 'com.example.eventTicket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdZsrB1QgXiPOKe-xjj6AlM44gK0TdNAY',
    appId: '1:214317871931:ios:77280a431234c300753d1e',
    messagingSenderId: '214317871931',
    projectId: 'ticket-event-edc21',
    storageBucket: 'ticket-event-edc21.firebasestorage.app',
    iosBundleId: 'com.example.eventTicket',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPxVGBgO8g8ysG8t2V6eMOXX3KBn1j5lY',
    appId: '1:214317871931:web:39e0585e37ae8f4d753d1e',
    messagingSenderId: '214317871931',
    projectId: 'ticket-event-edc21',
    authDomain: 'ticket-event-edc21.firebaseapp.com',
    storageBucket: 'ticket-event-edc21.firebasestorage.app',
    measurementId: 'G-WWHKGGGDFV',
  );

}