name: Dart

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Thiết lập Flutter SDK
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable' 

      - name: Install dependencies
        run: flutter pub get

      # Kiểm tra format code (tuỳ chọn)
      # - name: Verify formatting
      #   run: flutter format --set-exit-if-changed .

      - name: Analyze project source
        run: flutter analyze

      - name: Run tests
        run: flutter test

      - name: Flutter Build
        uses: AcmeSoftwareLLC/flutter-build@v1.0.2
        with:
          platform: android
